//initiate_grid
#macro STARTING_X_COORDINATE 100
#macro STARTING_Y_POSITION 100

#macro HORIZONTAL_GRID_LENGTH 6
#macro VERTICAL_GRID_HEIGHT 7

#macro STARTING_X_OFFSET 45
#macro TILE_WIDTH 90
#macro TILE_HEIGHT 90 
#macro TILE_Y_OFFSET 20

grid = []//[HORIZONTAL_GRID_LENGTH][VERTICAL_GRID_HEIGHT];
create_grid();//code in scr_create_grid